project_name: az-dns
builds:
- goos:
  - darwin
  - linux
  - windows
  goarch:
  - '386'
  - amd64
  - arm
  - arm64
  - mips
  - mips64
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: arm64
  main: .
  asmflags: >-
    all=-trimpath={{.Env.GOPATH}}
  gcflags: >-
    all=-trimpath={{.Env.GOPATH}}
  ldflags: >-
    all=-s -w -X github.com/elyscape/az-dns/cmd.version={{.Version}}
    -X github.com/elyscape/az-dns/cmd.commit={{.Commit}}
    -X github.com/elyscape/az-dns/cmd.date={{.Date}}
  env:
    - GOROOT_FINAL=/usr/local/go
archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if
    .Arm }}v{{ .Arm }}{{ end }}'
release:
  github:
    owner: elyscape
    name: az-dns
  name_template: '{{.Tag}}'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
