language: go
go:
  - "1.10"
  - master
matrix:
  allow_failures:
    - go: master
install:
  - make setup
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
