
[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "11.1.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.3.1"
